### ISSUE TITLE
Docs: Menu button is broken

### ISSUE THREAD

**Issue by mesqueeb** [ElMassimo/iles#10]
https://user-images.githubusercontent.com/3253920/138001960-1a4c966e-a589-4ddb-b0b5-589555662730.MOV

On mobile Safari the hamburger menu button does nothing. : )

**Comment by ElMassimo** [comment]
Thanks for reporting! Deployed a change that required an upgrade to `iles@0.3.2` but forgot to bump the dependencies.

Fixed in https://github.com/ElMassimo/iles/commit/c51184b262444f7cf0f5c5ce623f850409d523b1
