### ISSUE TITLE
The CJK content in the feed file generated is incorrectly encoded

### ISSUE THREAD

**Issue by kecrily** [ElMassimo/iles#100]
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖

_Provide a clear and concise description of what the bug is._

The CJK content in the feed file generated is incorrectly encoded. It opens locally without problems, but looks like a bunch of mess in the web

![image](https://user-images.githubusercontent.com/45708948/156613571-99260079-04e1-4ab2-9044-0334ae730fd9.png)

### Reproduction 🐞

_Please provide a link to a repo that can reproduce the problem you ran into._

Write something CJK content, like `你好世界`, then run `pnpm build`

<details>
<summary>Dependencies Info</summary>

_Run `npx iles info` and `pnpm list` (or `npm list`) and provide the output:_

```
devDependencies:
@iconify/json 2.1.10                   @vueuse/core 7.7.0
@islands/feed 0.1.2                    dayjs 1.10.8
@islands/icons 0.1.1                   iles 0.7.32
@islands/prism 0.1.1                   typescript 4.6.2
@unocss/preset-typography 0.26.4       unocss 0.26.4
@unocss/transformer-directives 0.26.4  vue-tsc 0.32.1
```
</details>

### Logs 📜

_If not providing a reproduction:_

<details>
<summary>Output</summary>

_Run `DEBUG=iles:* npm run dev` or `DEBUG=iles:* npm run build` and provide the output:_

```

```
</details>

### Screenshots 📷

_Provide console or browser screenshots of the problem_.

**Comment by ElMassimo** [comment]
Hi @kecrily, I'm not familiar with CJK. How should it be encoded?

**Comment by kecrily** [comment]
The browser incorrectly uses GBK (a Chinese encoding) to parse the Chinese content, which uses UTF-8, so it is garbled.

> By default the generated XML specifies utf-8.

Yes, but the browser does use GBK. I'm not sure why the browser automatically uses GBK to parse it.

**Comment by ElMassimo** [comment]
Did you try adding the site to [feedly](https://feedly.com/) and see if the content is parsed as expected?

**Comment by kecrily** [comment]
I have no problem opening `feed.atom` directly from the absolute address. But when I open it through `pnpm preview` server, the encoding is wrong.

I'm guessing it's a Vite problem.

**Comment by ElMassimo** [comment]
Gotcha, seems like it could be related to the headers (or lack of headers) provided to the browser by the Vite preview server.

It wouldn't affect the final result in production. Closing this one for now, but perhaps you can search in the Vite issue tracker to see if anyone has run into something similar in the past.
