### ISSUE TITLE
Feature: Ability to name islands

### ISSUE THREAD

**Issue by dhruvkb** [ElMassimo/iles#140]
**Is your feature request related to a problem? Please describe.**

Currently the islands are named in a very non-descript way like "App 2":

<img width="511" alt="Screenshot 2022-06-24 at 2 25 09 PM" src="https://user-images.githubusercontent.com/16580576/175516587-bf8a6de6-2f05-4f32-b76e-d8eb5f9f1c43.png">

This is fine for smaller applications with few islands but as the number of islands grows it'll be hard to keep track of islands by a number.

**Describe the solution you'd like**

A good solution would be to provide a way to name the individual islands. 

**Describe alternatives you've considered**

If a custom name API would be infeasible, the next best thing would be to name the island after the component it encapsulates.

**Comment by ElMassimo** [comment]
Being able to specify a custom name would require extending the `transform` logic, which is already complex.

I like the suggestion of naming them after the components, I've implemented auto-inferred names in #141.
