### ISSUE TITLE
"TypeError: error loading dynamically imported module" during hydration

### ISSUE THREAD

**Issue by gustojs** [ElMassimo/iles#15]
Thanks for working on this project! Here's the first result of trying it out.

Iles 0.3.2, Windows 10, Node 16.11.1. New project created with iles-create.

Provided following index page:
```
<template>
  <hello-world client:load />
</template>
```
and following HelloWorld.vue:
```
<template>
  <button @click="click">click me</button>
  <div>counter is now {{ counter }}</div>
</template>

<script setup lang="ts">
import { ref } from "vue";
const counter = ref(0);
function click() {
  counter.value++;
}
</script>
```
The button works but there are following console warnings:
```
Loading failed for the module with source “d:/my-project/src/components/HelloWorld.vue”.
Loading failed for the module with source “http://localhost:3000/@id/@islands/hydration”.
Loading failed for the module with source “http://localhost:3000/@id/@islands/hydration/vue”.
```

In case of `client:idle` or `client:visible`, the button doesn't work and the warnings are:
```
Loading failed for the module with source “d:/my=project/src/components/HelloWorld.vue”.
Uncaught (in promise) TypeError: error loading dynamically imported module
    component http://localhost:3000/
    resolveAndHydrate http://localhost:3000/@id/@islands/hydration:9
    hydrateWhenIdle http://localhost:3000/@id/@islands/hydration:14
```

All `client:load`, `client:idle`, and `client:visible` break during `npm run build` with the same error:
```
build error:
 TypeError: Cannot read properties of undefined (reading 'imports')
    at renderRoute (D:\my-project\node_modules\iles\dist\node\chunk-CGP66JQW.js:5250:17)  
    at D:\my-project\node_modules\iles\dist\node\chunk-CGP66JQW.js:5239:63
    at Array.map (<anonymous>)
    at bundleIslands (D:\my-project\node_modules\iles\dist\node\chunk-CGP66JQW.js:5239:36)
    at async D:\my-project\node_modules\iles\dist\node\chunk-4VENJ5VU.js:31:92
    at async withSpinner (D:\my-project\node_modules\iles\dist\node\chunk-U43AXZ2V.js:9:20)
    at async build (D:\my-project\node_modules\iles\dist\node\chunk-4VENJ5VU.js:31:5)
```
Without the client prop everything builds but of course there's no button handler.

**Comment by ElMassimo** [comment]
Hi Darek!

I was not able to replicate using a similar example. Would you provide a reproduction?

It might be Windows-related. Something that caught my eye is: `“d:/my=project`. That `=` sign is not present in the other paths?

**Comment by gustojs** [comment]
https://github.com/gustojs/iles-repro

It might as well be a Windows only issue, like you said.

**Comment by ElMassimo** [comment]
So it's not related with `\x00`. I'll do a prerelease patch so that you can test it. Thanks for all of your help!
