### ISSUE TITLE
Support for Vite v3

### ISSUE THREAD

**Issue by dhruvkb** [ElMassimo/iles#158]
**Is your feature request related to a problem? Please describe.**
Vite v3 has recently been released. iles currently depends on Vite v2.

**Describe the solution you'd like**
It'd be nice to upgrade the Vite dependency that's installed by iles to the new major version. This change might also entail a major version bump in iles itself.

**Describe alternatives you've considered**
We can stick with Vite v2 for a while but there is no alternative in the long term but to upgrade.

**Additional context**
The new release comes with a [migration guide](https://vitejs.dev/guide/migration.html).

**Comment by ElMassimo** [comment]
https://github.com/ElMassimo/iles/pull/147

**Comment by ElMassimo** [comment]
Released in [`iles@0.8.0`](https://github.com/ElMassimo/iles/blob/main/packages/iles/CHANGELOG.md#080-2022-07-14).
