### ISSUE TITLE
File names of dynamic routes in the build output should not be URI-encoded

### ISSUE THREAD

**Issue by ouuan** [ElMassimo/iles#167]
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖

The file names of dynamic routes are URI-encoded in the build output which breaks the links.

### Reproduction 🐞

https://github.com/ouuan/iles-uri-encoding-broken-link-demo

The build outputs:

```
dist
├── foo%20bar.html
├── foobar.html
├── index.html
└── static foo bar.html
```

Here `foo%20bar` is generated from a dynamic route, and `static foo bar` is a static route.

`/foo bar` breaks, and we need to access it via `/foo%2520bar`.

**Comment by ElMassimo** [comment]
Thanks for reporting! 

Probably encoded by [`routes.resolve` here](https://github.com/ElMassimo/iles/blob/main/packages/iles/src/node/build/routes.ts#L25).

Using `decodeURIComponent` when obtaining the [`outputFilename`](https://github.com/ElMassimo/iles/blob/main/packages/iles/src/node/build/routes.ts#L15) should fix it, and [`pathToFilename`](https://github.com/ElMassimo/iles/blob/main/packages/iles/src/node/build/utils.ts#L39-L44) is probably the best place to do that.

**Comment by ouuan** [comment]
I'm not sure how to handle the slash character 🤔 It seems that the slash should be encoded.

**Comment by ElMassimo** [comment]
Perhaps `path.split('/').map(decodeURIComponent).join('/')`?
