### ISSUE TITLE
Inline Style assets in HTML

### ISSUE THREAD

**Issue by iamandrewluca** [ElMassimo/iles#184]
**Is your feature request related to a problem? Please describe.**
Google Lighthouse reports direct loaded CSS as a blocking asset on most websites.

**Describe the solution you'd like**
Google Lighthouse recommends to inline critical CSS in HTML

**Describe alternatives you've considered**
Tried to use [`vite-plugin-singlefile`](https://github.com/richardtallent/vite-plugin-singlefile) plugin for Vite, but it throws an error

<details>
<summary>iles.config.ts</summary>

<img width="498" alt="image" src="https://user-images.githubusercontent.com/1881266/184843381-344c87b0-d6a9-4f7f-847a-82c96bbc9d85.png">

</details>

<details>
<summary>The Error</summary>

<img width="983" alt="image" src="https://user-images.githubusercontent.com/1881266/184843628-ea64b16f-548c-4356-ba30-c8c6efcbf8ce.png">

</details>

**Additional context**
https://github.com/vitejs/vite/issues/621
https://github.com/richardtallent/vite-plugin-singlefile

**Comment by ElMassimo** [comment]
`vite-plugin-singlefile` was designed for SPAs, where there's a single `index.html` file.

I'd recommend experimenting with a [custom `îles` module](https://iles-docs.netlify.app/guide/plugins#modules-and-plugins) that uses [`critters`](https://github.com/GoogleChromeLabs/critters) to inline the stylesheets using the [`ssg.beforePageRender`](https://iles-docs.netlify.app/config#ssg-beforepagerender) hook.

**Comment by iamandrewluca** [comment]
@ElMassimo 🤣 2 lines of code Carl, 2 lines

https://github.com/iamandrewluca/iamandrewluca.github.io/commit/6c922fc5185e86325dfaf2fde7a16bc1ac797c34

**Comment by ElMassimo** [comment]
Glad that it worked, thanks for sharing! 😃 

I think it would be useful to write a blog post about creating modules for îles.

**Comment by iamandrewluca** [comment]
I gave up on writing blog posts, it takes a lot of time. But here is a video 😀

https://youtu.be/Vu3LMe1RdfM

**Comment by ElMassimo** [comment]
Haha, great! But to clarify, I was thinking out loud, _I_ should write that post and add it to the docs 😄
