### ISSUE TITLE
Support useHead `body: true`

### ISSUE THREAD

**Issue by harlan-zw** [ElMassimo/iles#191]
**Is your feature request related to a problem? Please describe.**

[@vueuse/head](https://github.com/vueuse/head) recently added support for embedding scripts using `body: true` to add the script to the end of the body. ([commit](https://github.com/vueuse/head/commit/c5eed67b7c0eb6c70822ad25a96c84b93e4cf04d))

When using this feature in iles, the scripts don't get rendered at all. I'm guessing this is because the app template render is missing the `bodyTags` variable.

**Describe the solution you'd like**

Support for the option.

**Describe alternatives you've considered**

...

**Additional context**

...

**Comment by ElMassimo** [comment]
Hi Harlan!

Sounds good, adding support will require a simple change in the [`renderPage`](https://github.com/ElMassimo/iles/blob/main/packages/iles/src/node/build/render.ts#L57-L69) function.

**Comment by dhruvkb** [comment]
I also need it. Firefox weirdly shows FOUC when there isn't any script at the end of body. Even a blank `<script>/**/</script>` at `tagPosition: bodyClose` fixes it.
