### ISSUE TITLE
Fresh iles project not working with vite@3.1.0

### ISSUE THREAD

**Issue by davidlueder** [ElMassimo/iles#192]
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖
Vite v3.1.0 breaks the iles starter

### Reproduction 🐞
```
npm create iles@next
cd iles-app
npm install
npm run dev
```

### Workaround
```
npm create iles@next
cd iles-app
npm install -D --save-exact vite@3.0.9
npm install
npm run dev
```

### Logs
> Uncaught (in promise) Error: Page data not properly injected in app. Are you using it inside an island?
    at injectFromApp (pageData.js?v=de034eb9:12:15)
    at usePage (pageData.js?v=de034eb9:42:12)
    at Module.installDevtools (devtools.js:68:22)
    at @iles-entry:80:18

### Screenshots 📷
Browser console:
![image](https://user-images.githubusercontent.com/16711294/188605623-36ec8c83-3d61-45e7-bb3e-ea866b59875c.png)

**Comment by ElMassimo** [comment]
Hi David, thanks for reporting, seems like Vite `3.1.0` is duplicating the `iles` package in development:

<img width="210" alt="Screen Shot 2022-09-06 at 09 08 55" src="https://user-images.githubusercontent.com/1158253/188631410-ce6ef0ea-537b-4974-bf16-fcc07280fb46.png">

Looks like `iles build` still works as expected, I'll investigate for a potential fix.

**Comment by ElMassimo** [comment]
Fixed in Vite with:

- https://github.com/vitejs/vite/pull/10016

For now, `create-iles` will default to `vite@3.0.9` until the next release with the fix.
