### ISSUE TITLE
Option to output "pretty" HTML paths

### ISSUE THREAD

**Issue by lucperkins** [ElMassimo/iles#204]
Many static site generators enable you to output so-called "pretty" HTML paths, i.e. instead of `/about.html` they produce `/about/index.html`. I've been using iles a fair amount recently and haven't found a way to do this. If i"m mistaken, please let me know! Otherwise, this would be very nice to have, and I'd be happy to contribute this if you can provide some pointers on the best way to do so (i.e. should this be a Vite plugin? An iles plugin? Something built into iles?).

**Comment by userquin** [comment]
@lucperkins check https://iles-docs.netlify.app/config#prettyurls, by default true, you can disable it

**Comment by lucperkins** [comment]
@userquin Yes, precisely, I'd like everything generated as `index.html` files. To be honest, I think that people would expect setting `prettyUrls` to `true` to provide this. What would be the best way to contribute this option to the project? Happy to do so, as I don't think it'd be too difficult.

**Comment by ElMassimo** [comment]
Please see the discussion in this issue for reference:

- https://github.com/ElMassimo/iles/issues/195

---

I'd prefer îles to be explicit in terms of the structure of the HTML files it generates, if you want `/about/index.html`, create a `about/index.mdx` or `about/index.vue` page.

Have in mind most popular hosting options support routing `/about` to `/about.html`.

---

If you want this behavior, you could create a [module](https://iles.pages.dev/guide/plugins#modules-and-plugins) which uses the `extendRoutes` hook, allowing you to control the output.

**Comment by ElMassimo** [comment]
While inner-link checking is nice, I'd recommend checking all links in the built site, by using a tool such as [`lychee`](https://github.com/lycheeverse/lychee).

I typically use it in the CI after deploying, and it helps to detect any dead links, especially to third-party sites.
