### ISSUE TITLE
Cannot set dynamic page title on dynamic routes

### ISSUE THREAD

**Issue by dhruvkb** [ElMassimo/iles#223]
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖

Dynamic routes do not set page title. If 
```html
<page>
  title: My Page
</page>
```
is set, the title is hard-coded.

### Reproduction 🐞

<details>
<summary>Dependencies Info</summary>

_Run `npx iles info` and `pnpm list` (or `npm list`) and provide the output:_

```
iles v0.9.0 vite v4.0.3
```
</details>

**Comment by ouuan** [comment]
This is a question or a feature request. Why are you issuing a bug report? What's the correct behavior if you think it's a bug?

I'm modifying `page.frontmatter.title` to set the titles for dynamic routes, where `page` is `usePage()`.

**Comment by dhruvkb** [comment]
@ouuan you're right, this is a feature request. How can you set `page.frontmatter.title` in [`getStaticPaths()`](https://iles.pages.dev/guide/routing#generating-dynamic-routes)? I see that it returns only two keys, `params` (used to build the page HTML) and `props` (to populate the page) but not `frontmatter`.

**Comment by ouuan** [comment]
I use a separate script setup tag:

```vue
<script lang="ts">
export default definePageComponent({
  getStaticPaths() {
  },
});
</script>

<script setup lang="ts">
const page = usePage();
</script>
```

**Comment by ouuan** [comment]
But it seems that the extra tag is not needed for modifying the page frontmatter. I'm using it so that I can use other script setup features.

**Comment by dhruvkb** [comment]
I get what you're saying, thanks @ouuan! I'll close the issue because the feature exists.
