### ISSUE TITLE
Svelte vite plugin issue

### ISSUE THREAD

**Issue by TechAkayy** [ElMassimo/iles#239]
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖

Svelte is not rendering anymore. Getting [ERR_PACKAGE_PATH_NOT_EXPORTED] error when trying to start dev-server. 

### Reproduction 🐞

https://github.com/TechAkayy/nature-delights-with-iles

Stackblitz is not loading the above repo properly, so please clone the git repo to test. 

Due to current peer dependencies issue, to install use the force flag. Use command **npm install --force**

### Screenshots 📷

![image](https://user-images.githubusercontent.com/73772701/228150776-3d10d63a-6ddd-4a29-ac7b-305d2ce41429.png)

**Comment by ElMassimo** [comment]
Thanks for reporting!

In the meantime you could try rolling back the version of `vite-plugin-svelte` to [`1.0.9`](https://github.com/ElMassimo/iles/blob/2dae8a321f4e027e3b5769c9753054264b43b77e/packages/iles/package.json#L91).

**Comment by ElMassimo** [comment]
Released a fix in `iles@0.9.5`.
