### ISSUE TITLE
Expose unplugin-vue-components config to extend resolvers

### ISSUE THREAD

**Issue by TechAkayy** [ElMassimo/iles#244]
Would be good to have unplugin-vue-components exposed as a config (for eg, `autoImportComponents`), so that resolvers can be extended by users as required. These resolvers can be those shipped within unplugin-vue-components & those shipped part of component libraries. 

Something similar to vite's `mergeConfig` could be used to merge default & overrides.

For eg, 
```
import { defineConfig } from 'iles'
import NutUIResolver from '@nutui/nutui/dist/resolver'

export default defineConfig({
  siteUrl: 'https://iles-docs.netlify.app',
  jsx: 'preact',

  autoImportComponents: {
      resolvers: [
        NutUIResolver()
      ],
  },
})
```

**Comment by ElMassimo** [comment]
Hi!

This is already possible, see [`unplugin-vue-components`](https://iles.pages.dev/guide/plugins#unplugin-vue-components) in the _Plugins_ section of the docs.

**Comment by TechAkayy** [comment]
Ohh woww.. How did I miss it :-) Thanks Max!
