### ISSUE TITLE
Archive this project?

### ISSUE THREAD

**Issue by lucperkins** [ElMassimo/iles#273]
This project appears to be unmaintained and I would strongly suggest providing an indication of that in the README and also potentially by archiving the repo. As shown in #266, iles no longer builds properly. There have been no changes in 7 months, the most recent Actions runs have failed, etc.

This is really an awesome project and we loved using it for https://zero-to-nix.com. This is not an accusation; you do not owe us your continued time and attention. But a strong signal about the state of the project would courteously alert people that they shouldn't invest in it.

**Comment by ElMassimo** [comment]
Hi Luc!

Archiving the project would signal that I have no intention to resume development of the project, which is not the case.

As most solo efforts, there will be periods of time where life doesn't leave enough time for open source and the project stays unchanged, as well as periods where things move forward.

Anyone can fork it and fix build errors if they are inclined to do so, or continue using an older release, as I'm currently doing for all the sites I've created with this framework.

**Comment by lucperkins** [comment]
@ElMassimo Seems reasonable all around!

**Comment by nick-cjyx9** [comment]
> I would strongly suggest providing an indication of that in the README and also potentially by archiving the repo. 

+1

@ElMassimo I also think thst is rather important to indicate that in the documention and README till you resume development of the project. It is unable to create a runnable project through the starter. And dealing with dependencies problem really bothers me a lot now.

Hope everything goes well.
