### ISSUE TITLE
Not running docs

### ISSUE THREAD

**Issue by electroheadfx** [ElMassimo/iles#29]
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [X ] I have read the __[troubleshooting section]__ before opening an issue.
- [ X] I have tried upgrading `iles` and `vite`.

### Description 📖

Iam not able to run in local the docs, for test, maybe Iam wrong with the setup.
I tried with npm and pnpm, no luck. thanks

error starting server:
 Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@islands/headings' imported from /Users/efxair/Desktop/dev/iles/node_modules/.pnpm/iles@0.5.2/node_modules/iles/lib/modules.js
Did you mean to import /Users/efxair/Desktop/dev/iles/packages/headings/src/headings.cjs?

Any typo error in : docs/src/components/Image.vue 
line 5: -narrow: { type: Boolean, defalt: false },
line 6: -wide: { type: Boolean, defalt: false },
Should be:
line 5: +narrow: { type: Boolean, default: false },
line 6: +wide: { type: Boolean, default: false },

### Reproduction 🐞

<details>

git clone https://github.com/ElMassimo/iles.git
cd iles
npm i
cd docs
npm i

</details>

### Logs 📜

error starting server:
 Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@islands/headings' imported from /Users/efxair/Desktop/dev/iles/node_modules/.pnpm/iles@0.5.2/node_modules/iles/lib/modules.js
Did you mean to import /Users/efxair/Desktop/dev/iles/packages/headings/src/headings.cjs?

Any typo error in : docs/src/components/Image.vue 
line 5: -narrow: { type: Boolean, defalt: false },
line 6: -wide: { type: Boolean, defalt: false },
Should be:
line 5: +narrow: { type: Boolean, default: false },
line 6: +wide: { type: Boolean, default: false },

**Comment by ElMassimo** [comment]
Hi Laurent!

Please provide additional information about your environment, such as node version and operating system version.

---

All the projects under this repo are setup using `pnpm`. You can use `npm` if you [create a new project](https://github.com/ElMassimo/create-iles).

I'm using node `v14.7.0` and `v16.5.0` locally and I haven't experienced that error. Netlify is auto-deploying correctly as well, both with Node 16 and 14:

```
Now using node v14.18.1 (npm v6.14.15)
```

**Comment by electroheadfx** [comment]
```
efxpro:dev efxair$ node -v
v16.4.2
efxpro:dev efxair$ npm -v
7.18.1
efxpro:dev efxair$ pnpm -v
6.20.1

```
seem Iam too high for node ?

Mac Mojave 10.14.6

**Comment by ElMassimo** [comment]
A more recent node should't be a problem. Netlify:

```
Now using node v16.13.0 (npm v8.1.0)
```

Perhaps try starting a new project and see if you run across the same error?

**Comment by electroheadfx** [comment]
wow it works now, great from you, I can look now how it works, thanks :)
