### ISSUE TITLE
Having a layout name starting with capital letter will make the build crash

### ISSUE THREAD

**Issue by gawlk** [ElMassimo/iles#30]
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖

Basically the title

### Reproduction 🐞

_Please provide a link to a repo that can reproduce the problem you ran into._

You'd have to try it yourself I suppose

<details>
<summary>Dependencies Info</summary>

_Run `npx iles info` and `pnpm list` (or `npm list`) and provide the output:_

```

```
</details>

### Logs 📜

_If not providing a reproduction:_

<details>
<summary>Output</summary>

_Run `DEBUG=iles:* npm run dev` or `DEBUG=iles:* npm run build` and provide the output:_

```

```
</details>

### Screenshots 📷

_Provide console or browser screenshots of the problem_.

<img width="1171" alt="Screenshot 2021-11-05 at 09 40 26" src="https://user-images.githubusercontent.com/32246972/140482451-234f2a49-331f-450b-8a45-8db2ea88bc82.png">

As you can see it's looking for `centered.vue` while the actual file was named `Centered.vue`, changing the filename to `centered.vue` fixed the issue

**Comment by ElMassimo** [comment]
Hi Kevin, thanks for reporting!

I'll keep this open as a reminder to update the docs and ensures this fails in development as well.

Layout files must always be lowercase.
