### ISSUE TITLE
Relative paths for srcset not working

### ISSUE THREAD

**Issue by HerrBertling** [ElMassimo/iles#35]
- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖

Hey :wave: When using a `picture` element, it seems as if the `src` for the `img` is resolved correctly, but the `srcset` attribute for different `source` tags is not resolved when using `~` or `@`.

### Reproduction 🐞

```html
<picture>
    <source
      srcset="
        @/assets/images/some_image_2x.png 2x,
        @/assets/images/some_image.png
      "
      type="image/png"
    />
    <source
      srcset="
        @/assets/images/some_image_2x.webp 2x,
        @/assets/images/some_image.webp
      "
      type="image/webp"
    />
    <img
      loading="lazy"
      src="@/assets/images/some_image.png"
    />
  </picture>
```

This will result in this code, at least in dev mode (haven't checked the `build` but my guess is that it's incorrect there as well):

```html
<picture>
    <source
      srcset="
        /src/components/@/assets/images/some_image.png 2x,
        /src/components/@/assets/images/some_image.png"
      type="image/png"
    >
    <source
      srcset="
        /src/components/@/assets/images/some_image_2x.webp 2x,
        /src/components/@/assets/images/some_image.webp"
      type="image/webp"
    >
    <img
      loading="lazy"
      src="/src/assets/images/some_image.png"
    >
  </picture>
```

<details>
<summary>Dependencies Info</summary>

```
iles v0.6.4 vite v2.6.14
```
</details>

**Comment by ElMassimo** [comment]
Hi Markus!

îles does not alter how Vue or `@vitejs/plugin-vue` do import analysis. It's likely that it hasn't been implemented for that format of `srcset` (with two paths).

Please visit the Vite.js Discord to check, or open an issue in Vite.

---

In the meantime, for MDX you can use [`remark-mdx-images`](https://www.npmjs.com/package/remark-mdx-images), and in Vue files, you can manually import the image sources and bind them:

```js
import someImageSrc from '@/assets/images/some_image.png'
```

```fue
<source :srcset="someImage" type="image/png">
```

**Comment by ElMassimo** [comment]
@HerrBertling About your question about global CSS, the best approach is to import it in [`src/app.ts`](https://iles-docs.netlify.app/config#your-app). Plan to document this soon in a _Recipes section_ in the docs.

See the following examples:

- [Docs](https://github.com/ElMassimo/iles/blob/main/docs/src/app.ts#L3)
- [The Vue Point](https://github.com/ElMassimo/iles/blob/main/playground/the-vue-point/src/app.ts#L5)

**Comment by ElMassimo** [comment]
@HerrBertling [This is the relevant code](https://github.com/vuejs/vue-next/blob/master/packages/compiler-sfc/src/templateTransformSrcset.ts#L38) regarding srcset transforms in Vue.

**Comment by HerrBertling** [comment]
Wow. Thanks for the answers ❤️
