### ISSUE TITLE
Incremental Static (Re)Generation

### ISSUE THREAD

**Issue by pbuzdin** [ElMassimo/iles#39]
Generate and regenerate only pages and partials which should be updated.

**Additional context**
https://vercel.com/docs/concepts/next.js/incremental-static-regeneration

**Comment by ElMassimo** [comment]
> Incremental builds 

Do you mean incremental rendering?

It's possible to generate an additional script during build that can be used to render [dynamic routes](https://iles-docs.netlify.app/guide/routing#dynamic-routes) [that were not prerendered](https://docs.layer0.co/guides/isg#section_adding_isg_to_an_app_built_with_any_framework) in `getStaticPaths`.

As to integrating specifically with providers like Vercel, or Netlify, that's out of scope for the core of îles, and can be implemented as [modules](https://iles-docs.netlify.app/config/plugins).
